### ISSUE TITLE
Use stone to auto generate functions and data types

### ISSUE THREAD

**Issue by braincore** [Alorel/dropbox-v2-php#4]
We use a tool called [Stone](https://github.com/dropbox/stone) to automatically generate large portions of our Dropbox SDKs from these [specs](https://github.com/dropbox/dropbox-api-spec). It would be great if this library could use Stone as well, which has an upfront cost, but really reduces maintenance burden. See the [Dropbox Python SDK](https://github.com/dropbox/dropbox-sdk-python) for an example.

Thanks for making this SDK by the way!

**Comment by Alorel** [comment]
Hey!

Thanks for the tip, I will consider it in the future, but right now I have everything set up as a template in my IDE and any changes are simply delegated to extending classes, so I don't see it as a priority.

I've got very little free time for development these days so I want to spend it on getting things to work instead of the upfront cost you mentioned. :)
